# Generated by Django 2.2.5 on 2019-09-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190914_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
