# Generated by Django 2.2.5 on 2019-09-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('users', '0004_learner_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='learners', to='grades.Grade'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='form_class',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='grades.Grade'),
        ),
    ]
