# Generated by Django 2.2.5 on 2019-09-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190916_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_user',
            field=models.BooleanField(default=True),
        ),
    ]
