# Generated by Django 2.2.5 on 2019-09-16 12:01

from django.db import migrations, models
import django.db.models.deletion
import grades.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_year', '0002_auto_20190916_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.PositiveIntegerField(validators=[grades.models.get_maximum_section])),
                ('branch', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic_year.AcademicYear')),
            ],
            options={
                'ordering': ('year', 'section', 'branch'),
                'unique_together': {('year', 'section', 'branch')},
            },
        ),
    ]
