# Generated by Django 2.2.5 on 2019-09-19 11:51

import discipline.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_user_current_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_type', models.CharField(choices=[('M', 'Merit'), ('D', 'Demerit')], max_length=1)),
                ('code', models.CharField(max_length=7, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('point', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('point', 'code'),
            },
        ),
        migrations.CreateModel(
            name='DisciplineAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=discipline.models.get_discipline_action_time)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_action', to='discipline.Discipline')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_action', to='users.Learner')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_action', to='users.Teacher')),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
