# Generated by Django 2.2.5 on 2019-09-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(default='Grade', max_length=25)),
                ('update_grades', models.BooleanField(default=True, verbose_name='Move learners to the next grade at the start of the new academic year.')),
                ('last_section', models.PositiveIntegerField(default=12, help_text='Learners will not be updated for the next academic year after this division.')),
                ('allow_alumni', models.BooleanField(default=True, verbose_name='Move learners in the last section to alumni section at the end of academic year. ')),
                ('allow_transfers', models.BooleanField(default=True, verbose_name='Add learner to transferred section in case of de-registration')),
                ('allow_expulsion', models.BooleanField(default=True, verbose_name='Add learner to expelled section in case of expulsion.')),
            ],
        ),
    ]
