# Generated by Django 2.2.5 on 2019-09-16 07:32

import academic_year.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2019, help_text='Please add new academic year greater than 2019 in 4-digit format.', unique=True, validators=[academic_year.models.validate_year], verbose_name='academic year')),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
