# Generated by Django 2.2.5 on 2019-09-16 12:01

import academic_year.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_year', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.PositiveIntegerField(default=2019, help_text='Add new academic year greater than 2019 in 4-digit format.', unique=True, validators=[academic_year.models.validate_year], verbose_name='academic year'),
        ),
    ]
